name: Deploy Docker Image to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Set up Azure CLI (updated to v2)
      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v2
        with:
          azure-cli-version: '2.30.0'

      # Log in to Azure using Service Principal Authentication
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      # Create Resource Group (if needed)
      - name: Create Resource Group
        run: |
          az group create --name my-resource-group --location eastus
        
      # Create App Service Plan
      - name: Create App Service Plan
        run: |
          az appservice plan create --name my-app-service-plan --resource-group my-resource-group --sku B1 --is-linux
        
      # Create Web App
      - name: Create Web App
        run: |
          az webapp create --name my-web-app --resource-group my-resource-group --plan my-app-service-plan --deployment-container-image-name <your_dockerhub_username>/<image_name>:<tag>
        
      # Configure App Service for Docker Image
      - name: Configure App Service for Docker Image
        run: |
          az webapp config container set --name my-web-app --resource-group my-resource-group --docker-custom-image-name <your_dockerhub_username>/<image_name>:<tag> --docker-registry-server-url https://index.docker.io/v1/
        
      # Optional: Restart App Service
      - name: Restart App Service
        run: |
          az webapp restart --name my-web-app --resource-group my-resource-group
